iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')) 
choco install 7zip.install
choco install agentransack
choco install beyondcompare
choco install chocolateygui
choco install colorPic
choco install composer
choco install curl
choco install ditto.install
choco install dotnet4.7
choco install git.install
choco install greenshot
choco install iperf3
choco install MobaXTerm
choco install nircmd
choco install nodejs.install
choco install notepad2
choco install php
choco install powerShell
choco install sourcetree
choco install sumatrapdf.install
choco install sysinternals
choco install visualstudiocode
choco install vlc
choco install wget
choco install winscp
